/**
 * Detect custom queries from parsed schema and build stub resolvers.
 *
 * Custom queries are those defined in the schema that aren't auto-generated
 * get/list/GSI queries. They typically come from .query() definitions in the
 * Amplify schema and may reference Lambda handlers.
 *
 * Stub resolvers return empty results in the expected return type shape.
 * Config overrides (config.customResolvers) replace stubs with user functions.
 *
 * @param {object} parsedSchema - Parsed schema from the parser
 * @param {object} config - Config with optional customResolvers map
 * @returns {{ queryResolvers: object, querySDL: string[] }}
 */
export function buildCustomQueryResolvers(parsedSchema, config) {
  const autoQueries = buildAutoQuerySet(parsedSchema);
  const customQueries = findCustomQueries(parsedSchema);
  const customResolvers = config.customResolvers || {};

  const queryResolvers = {};
  const querySDL = [];

  for (const query of customQueries) {
    // Skip if this is an auto-generated query
    if (autoQueries.has(query.name)) continue;

    // Use config override if provided, otherwise stub
    if (customResolvers[query.name]) {
      queryResolvers[query.name] = customResolvers[query.name];
    } else {
      queryResolvers[query.name] = createStubResolver(query);
    }

    // Generate SDL for the custom query if not already in the schema
    if (query.sdl) {
      querySDL.push(query.sdl);
    }
  }

  return { queryResolvers, querySDL };
}

/**
 * Build the set of auto-generated query names from the parsed schema.
 */
function buildAutoQuerySet(parsedSchema) {
  const names = new Set();

  for (const [modelName, model] of Object.entries(parsedSchema.models)) {
    names.add(`get${modelName}`);
    names.add(`list${pluralize(modelName)}`);

    for (const idx of model.secondaryIndexes || []) {
      const queryName = idx.queryField || `list${modelName}By${capitalize(idx.partitionKey)}`;
      names.add(queryName);
    }
  }

  return names;
}

/**
 * Find custom queries defined in the parsed schema.
 *
 * Custom queries may appear as entries in parsedSchema.customQueries,
 * or as additional query fields on models that don't match the standard
 * get/list/GSI pattern.
 */
function findCustomQueries(parsedSchema) {
  const queries = [];

  // Check for explicitly defined custom queries
  if (parsedSchema.customQueries) {
    for (const [name, def] of Object.entries(parsedSchema.customQueries)) {
      queries.push({
        name,
        returnType: def.returnType || 'AWSJSON',
        args: def.args || {},
        sdl: null, // SDL already generated by schema-generator if in parsed schema
      });
    }
  }

  // Check for custom query types on models (e.g., model-level custom operations)
  if (parsedSchema.customTypes) {
    for (const [name, def] of Object.entries(parsedSchema.customTypes)) {
      queries.push({
        name,
        returnType: def.returnType || 'String',
        args: def.args || {},
        sdl: null,
      });
    }
  }

  return queries;
}

/**
 * Create a stub resolver for a custom query that returns empty/default results.
 */
function createStubResolver(query) {
  return async (_parent, args, _context) => {
    // Return an appropriate empty value based on the return type
    const rt = query.returnType;

    if (rt === 'AWSJSON' || rt === 'String') {
      return JSON.stringify({ message: `Stub response for ${query.name}`, args });
    }

    // If the return type looks like a connection type, return empty items
    if (rt.endsWith('Connection')) {
      return { items: [], nextToken: null };
    }

    // If the return type looks like an array
    if (rt.startsWith('[')) {
      return [];
    }

    // Default: return null
    return null;
  };
}

function capitalize(str) {
  if (!str) return str;
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function pluralize(name) {
  if (!name) return name;
  const irregulars = {
    Person: 'People', Child: 'Children', Mouse: 'Mice',
    Goose: 'Geese', Man: 'Men', Woman: 'Women',
    Foot: 'Feet', Tooth: 'Teeth',
  };
  if (irregulars[name]) return irregulars[name];
  if (/[^aeiou]y$/i.test(name)) return name.slice(0, -1) + 'ies';
  if (/(?:s|x|z|sh|ch)$/i.test(name)) return name + 'es';
  return name + 's';
}
